name: Lint Naftiko Capabilities

on:
  push:
    branches:
        - 'feat/update-validate-github-action-with-megalinter'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oxsecurity/megalinter@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true