name: Publish Maven to sonatype and GitHub Packages

on:
  release:
    types: [published]
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  github-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      
      - name: Prepare shared path
        run: ln -s ikanos-engine/src/test/resources/tutorial/shared shared

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Strip SNAPSHOT
        run: mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false

      - name: Publish to GitHub Packages (release)
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  maven-central:
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Prepare shared path
        run: ln -s ikanos-engine/src/test/resources/tutorial/shared shared

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure Maven Central
        run: ./scripts/builder.sh config_maven_central
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}

      - name: Configure GPG
        run: ./scripts/builder.sh config_gpg
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Maven Central
        run: ./scripts/builder.sh central
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Cleanup
        if: always()
        run: |
          rm -rf ~/.gnupg
          rm -f ~/.m2/settings.xml


  github-snapshot:
    if: github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Prepare shared path
        run: ln -s ikanos-engine/src/test/resources/tutorial/shared shared
        
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Get version
        run: echo "VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

      - name: Publish snapshot
        if: contains(env.VERSION, 'SNAPSHOT')
        run: mvn --batch-mode -Dgpg.skip=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}